# Generated by Django 5.0.4 on 2024-04-13 05:55

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                ("author", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(blank=True, max_length=512, null=True),
                ),
                (
                    "price",
                    models.IntegerField(validators=[api.validators.validate_price]),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column_name",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["column_name"],
            },
        ),
    ]
